name: Build zfs-on-wsl using an Ubuntu LTS container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04

    steps:
      - name: Run zfs-on-wsl buildscript
        run: ./zfs-on-wsl.sh
